[package]
name = "core"
version = "0.1.0"
authors = ["https://github.com/discuzz-labs"]
edition = "2018"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
